spring.application.name=Event-booking

spring.datasource.url=jdbc:postgresql://localhost:5432/event_booking
spring.datasource.username=event_user
spring.datasource.password=event_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true